### PR TITLE
report child process exit status according to config parameter

### LINKED ISSUE #3281: Log child process reaping if processes terminated abnormally or with non-zero exit code
### Desired behavior
Informational logging of reaped child process should be supressed if the process exited normally with an exit code of zero.

### Actual behavior
All reaped child process exits are logged irrespective of whether the process died unexpectedly or exited with a non-zero error code.

### Steps to reproduce the behavior
Create a rotation script that is invoked once a log file reaches some arbitrary size (e.g. 10000 bytes). Create a logging rule to invoke the rotation script. Once the file is rotated, a "Child XXX has terminated, reaped by main-loop" will be shown in the new log file.

### Environment
```
rsyslogd 8.37.0, compiled with:
	PLATFORM:				arm-tait-linux-gnueabi
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	No
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				No
	systemd support:			No
	Number of Bits in RainerScript integers: 64
```
The platform is a custom OpenEmbedded platform.

## Suggested implementation
Modify the mainloop function to supply a pointer to a status variable in the call to waitpid()  and examine its value on return. Only log a message if:
* `WIFEXITED(status)` returns `false`, or
* `WEXITSTATUS(status)` returns a non-zero value.

### PR DESCRIPTION
**Pull request by jsiwrk**
Add new global setting 'reportChildProcessExits' with possible values
'none|errors|all' (default 'errors'), and new global function
'glblReportChildProcessExit' to report the exit status of a child
process according to the setting.

Invoke the report function whenever rsyslog reaps a child, namely in:
- rsyslogd.c (SIGCHLD signal handler)
- omprog
- mmexternal
- srutils.c (execProg function, invoked from stream.c and omshell)

Remove redundant "reaped by main loop" info log in omprog.

Promote debug message in mmexternal indicating that the child has
terminated prematurely to a warning log, like in omprog.

Closes #3281

### CODE REVIEW

File: runtime/glbl.c [hunk 1]
```diff
@@ -1337,31 +1404,31 @@ glblDoneLoadCnf(void)
...
+	        loadConf->globals.gidDropPrivKeepSupplemental = (int) cnfparamvals[i].val.d.n;
 		} else if(!strcmp(paramblk.descr[i].name, "net.acladdhostnameonfail")) {
-		        *(net.pACLAddHostnameOnFail) = (int) cnfparamvals[i].val.d.n;
+	        *(net.pACLAddHostnameOnFail) = (int) cnfparamvals[i].val.d.n;
 		} else if(!strcmp(paramblk.descr[i].name, "net.aclresolvehostname")) {
-		        *(net.pACLDontResolve) = !((int) cnfparamvals[i].val.d.n);
+	        *(net.pACLDontResolve) = !((int) cnfparamvals[i].val.d.n);
 		} else if(!strcmp(paramblk.descr[i].name, "net.enabledns")) {
-		        setDisableDNS(!((int) cnfparamvals[i].val.d.n));
+	        setDisableDNS(!((int) cnfparamvals[i].val.d.n));
```
Comment (rgerhards) [inline runtime/glbl.c]: any specific reason you removed the indention? With it, the code is far more readable.

File: tests/omprog-restart-terminated-outfile.sh [hunk 2]
```diff
@@ -71,7 +71,7 @@ injectmsg 6 1
 injectmsg 7 1
 wait_queueempty
 
-kill -s USR1 $(get_child_pid)
+kill -s KILL $(get_child_pid)
```
Comment (rgerhards) [inline tests/omprog-restart-terminated-outfile.sh:74]: a word of caution: we are moving towards supporting parallel builds, as well es parallel execution of multiple CI runs on the same worker. I think the current `get_child_pid` implementation will not work in that environment. It would probably be good to change this to using child-created pidfiles some time in the future.

File: tests/omprog-restart-terminated-outfile.sh [hunk 3]
```diff
@@ -71,7 +71,7 @@ injectmsg 6 1
...
 ./msleep 100
```
Comment (rgerhards) [inline tests/omprog-restart-terminated-outfile.sh:75]: We should try to avoid sleep calls - past months experience tells they work exceptionally bad when CI is pretty busy. We have lot's of failures because of this. Again, this is nothing specific to the PR, just sharing info.

File: tests/testsuites/omprog-restart-terminated-bin.sh [hunk 4]
```diff
@@ -34,7 +34,7 @@ while [[ -n "$log_line" ]]; do
         # Terminate prematurely by closing pipe, without confirming the message
         echo "Terminating without confirming the last message" >> $outfile
         >&2 echo "[stderr] Terminating without confirming the last message"
-        exit 1
+        exit 0
```
Comment (rgerhards) [inline tests/testsuites/omprog-restart-terminated-bin.sh:37]: is this more an `exit 77` (SKIP test)?

File: runtime/glbl.c (hunk 1 above)
Comment (jsiwrk) [reply runtime/glbl.c]: Actually I corrected the indention... After careful inspection, though, these lines had some spaces instead of tabs. GitHub was displaying a different indention than my editor because of the tab size (8 in GitHub instead of 4 in my editor). I have replaced the spaces with tabs and updated the PR.

BTW, do you have a specific convention for the tab size in which the code is supposed to be viewed? Sometimes there can be differences, as in this case. (Note: people advocate for avoiding the use of tabs in open source projects to avoid this kind of issues, although I personally have no problem with them...)

File: tests/omprog-restart-terminated-outfile.sh (hunk 2 above)
Comment (jsiwrk) [reply tests/omprog-restart-terminated-outfile.sh:74]: If you recall, we already took that into consideration time ago in that test (and similar others). Please see some lines above:
```
# We need a test-specific program name, as the test needs to signal the child process
cp -f $srcdir/testsuites/omprog-restart-terminated-bin.sh $RSYSLOG_DYNNAME.omprog-restart-terminated-bin.sh

# On Solaris 10, the output of ps is truncated for long process names; use /usr/ucb/ps instead:
if [[ $(uname) = "SunOS" && $(uname -r) = "5.10" ]]; then
    function get_child_pid {
        echo $(/usr/ucb/ps -awwx | grep "$RSYSLOG_DYNNAME.[o]mprog-restart-terminated-bin.sh" | awk '{ print $1 }')
    }
else
    function get_child_pid {
        echo $(ps -ef | grep "$RSYSLOG_DYNNAME.[o]mprog-restart-terminated-bin.sh" | awk '{ print $2 }')
    }
fi
```
I.e. the program is renamed prior to spawning it by adding the test runtime random prefix. So in case of a parallel test execution, each test would have its own process name. (Note: because of the long process name, I had to use an alternate way to get the child PID in Solaris 10, as shown above.) Am I missing something?

> It would probably be good to change this to using child-created pidfiles some time in the future.

OK, seems a good idea since that would eliminate the need for the use of ps and also the Solaris special case. The pid file itself would also need to have a random name, though. Taking note of this as a future improvement.

File: tests/omprog-restart-terminated-outfile.sh (hunk 3 above)
Comment (jsiwrk) [reply tests/omprog-restart-terminated-outfile.sh:75]: I know sleeps are not desirable... When I refactored the omprog tests in #2629 I eliminated most of them, and as far as I know the tests have been stable since then (please tell me otherwise). However I left that one (which ensures that the child processes the signal before receiving the next message) to keep the test code simpler, and because it seems very unlikely that the test could break because of this... Taking note of this as a possible future improvement, though.

File: tests/testsuites/omprog-restart-terminated-bin.sh (hunk 4 above)
Comment (jsiwrk) [reply tests/testsuites/omprog-restart-terminated-bin.sh:37]: No, this code belongs to a test program started by the test, so the special exit codes for tests don't apply here. (Note: I changed the exit code in that line from 1 to 0 to test that the new global flag does not log normal exits.)

**Comment by jsiwrk** [comment]
The LGTM analysis failure seems not my fault... Please tell me otherwise.

File: tests/omprog-restart-terminated-outfile.sh (hunk 3 above)
Comment (rgerhards) [reply tests/omprog-restart-terminated-outfile.sh:75]: just dispensing info: we have machines where, when under stress, operations take up to 6..7 times longer than I had expected (and anticipated in the tests).

**Comment by rgerhards** [comment]
interestingly, the LGTM failure seems to return with a new push - restarted, let's see what happens next

@jsiwrk do you plan to do any more work on the PR? Else it would be good to update the doc so that we can finally merge :-)

**Comment by jsiwrk** [comment]
OK, will update the docs soon.

Note: I resolved the last conflict using the GitHub UI and I've had a hard time squashing and rebasing the merge commit... Will not use that option again.

**Comment by rgerhards** [comment]
@jsiwrk I think these are valid: https://www.codefactor.io/repository/github/rsyslog/rsyslog/pull/3328

**Comment by rgerhards** [comment]
@jsiwrk the _codecov builder was originally not running omprog tests for some reason I had forgotten. I have re-enabled it, and now I see all sorts of test failures related to omprog tests: http://build.rsyslog.com/testbench-showtest.php?testname=omprog%

Maybe you have an idea? I can of course turn omprog testing off again, but it looks like there indeed is something wrong.

**Comment by jsiwrk** [comment]
> I see all sorts of test failures related to omprog tests: http://build.rsyslog.com/testbench-showtest.php?testname=omprog%

It seems the failures are:
- the failure in `omprog-output-capture-mt.sh` since v8.40, described in #3361 (see there for details)
- failures in multiple valgrind tests, like the following one. The stack trace seems to indicate this is due to a recent change in the core. Also, note that the valgrind tests of other plugins are also detecting this. Therefore it doesn't seem related to omprog or the omprog tests. I've not investigated further.
  ```
    main Q:Reg: enter WrkrExecCleanup
    ==2580== Thread 6 rs:main Q:Reg:
    ==2580== Invalid read of size 8
    ==2580==    at 0x44A30E: wtpWorker (wtp.c:381)
    ==2580==    by 0x5053E24: start_thread (in /usr/lib64/libpthread-2.17.so)
    ==2580==    by 0x5FB7BAC: clone (in /usr/lib64/libc-2.17.so)
    ==2580==  Address 0x8274830 is 304 bytes inside a block of size 312 free'd
    ==2580==    at 0x4C2AD1D: free (vg_replace_malloc.c:530)
    ==2580==    by 0x44A00F: wtpDestruct (wtp.c:179)
    ==2580==    by 0x44F158: qqueueDestruct (queue.c:2737)
    ==2580==    by 0x40E018: deinitAll (rsyslogd.c:2009)
    ==2580==    by 0x40E018: main (rsyslogd.c:2119)
    ==2580==  Block was alloc'd at
    ==2580==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
    ==2580==    by 0x44A3F5: wtpConstruct (wtp.c:116)
    ==2580==    by 0x4504A3: qqueueStart (queue.c:2466)
    ==2580==    by 0x40F1A5: startMainQueue (rsyslogd.c:834)
    ==2580==    by 0x42EB84: activateMainQueue (rsconf.c:808)
    ==2580==    by 0x42EB84: activate (rsconf.c:874)
    ==2580==    by 0x41014B: initAll (rsyslogd.c:1624)
    ==2580==    by 0x40DE97: main (rsyslogd.c:2110)
  ```
- some failures in `omprog-feedback-mt.sh` like the following. There is a core dump and an error indicating a possible "double free". I think it is related to the above error detected by valgrind. Probably this memory error affects high-load tests (like this one) more than others. I've not investigated further.
   ```
    rsyslogd: omprog: error sending message to program: Bad file descriptor [v8.1901.0.master try https://www.rsyslog.com/e/2119 ]
    rsyslogd: omprog: error sending message to program: Bad file descriptor [v8.1901.0.master try https://www.rsyslog.com/e/2119 ]
    rsyslogd: omprog: error sending message to program: Bad file descriptor [v8.1901.0.master try https://www.rsyslog.com/e/2119 ]
    rsyslog debug: omprog_action queue:Reg/w5: enter WrkrExecCleanup
    rsyslog debug: 0x563046a921a0: worker exiting
    double free or corruption (fasttop)
    ./diag.sh: line 495: 24197 Aborted                 (core dumped) LD_PRELOAD= ../tools/rsyslogd -C -n -irstb_817200_3149925e:.pid -M../runtime/.libs:../.libs -frstb_817200_3149925e_.conf
    imdiag[39495]: ./diag.sh: line 726: kill: (24197) - No such process
    13:40:46 wait on shutdown of 24197
    unexpected line count in omprog script output: 9744 (expected: 10000)
   ```

**Comment by jsiwrk** [comment]
> @jsiwrk I think these are valid: https://www.codefactor.io/repository/github/rsyslog/rsyslog/pull/3328

Corrected in PR #3373.

**Comment by rgerhards** [comment]
@jsiwrk I think the valgrind issue has been fixed by https://github.com/rsyslog/rsyslog/pull/3359

File: runtime/glbl.c (hunk 1 above)
Comment (rgerhards) [reply runtime/glbl.c]: we use the default tab size of 8 (and sorry for the delay, I overlooked the question and have come over it "by accident" now...). The rule we use is "indent by tab" and "indent any follow-up (of an incomplete) line by another tab" - this is always consistent no matter of the tab size. It just get's messi when trying to pretty-print.

Tabs or spaces is sometime religious . while I personally prefer tabs (everybody is free to adjust as according to his personal taste), rsyslog always used tabs (even when I inherited it) and this is why we kept it this way. Re-writing them would wreck git history usefulness (would look like a complete rewrite).

**Comment by jsiwrk** [comment]
The failure of the omprog test with the _codecov builder is being analyzed in issue #3361. I think this PR could be merged (when deemed appropriate) independently of that, since it is unrelated.

**Comment by rgerhards** [comment]
@jsiwrk mhhh... looks like codecov worker still fails, even though I have merged the other patch set :-S

**Comment by jsiwrk** [comment]
Yes, this is expected since the issue has not been corrected yet. Please recall my comments in the patch...

**Comment by rgerhards** [comment]
@jsiwrk sry, been working on a couple of CI issues in parallel... Did you have a chance to see if clang coverage shows the same issues? If not, I can probably give it a try.

**Comment by jsiwrk** [comment]
No, I will probably not be available in the short term, sorry... I would bet it's a problem with the gcc instrumentation, but proving this will require time, since we must craft a minimal program that reproduces the problem (and of course it could also be a problem in the omprog code... but it doesn't seem so). Apart from looking at clang, a provisional workaround that could work would be to use Ubuntu 16.04 (instead of 18.04) in the codecov builder, since I couldn't reproduce the problem on that Ubuntu version. I know that's not acceptable as a permanent solution, but in the meantime...

**Comment by rgerhards** [comment]
@jsiwrk I tried `gcc-8` inside the Ubuntu 18.04 container. This did not help. So if it is a gcc bug, it's a long-standing one. Next is to try clang, which I am pretty positive about...

I would not like to switch to Ubuntu 16.04, as it is hard to get full coverage for the older builds. But we can do (and do!) runs on multiple platforms. Anyhow, it kind of feels strange to fallback to old stuff when not 100% sure why this is needed.

**Comment by rgerhards** [comment]
gcc8 check not required here as it was not present when PR came in (and so I can't trigger it). Also, I know 99.99999% sure it will pass.

**Comment by rgerhards** [comment]
@jsiwrk ¡finally! - with clang, coverage reporting seems to work; ok, I had to disable the helgrind tests, but that is not a real problem. So I am able to finally merge. 

Note, thought, that while it looks like a gcc bug, I am not 100% sure - especially as the bug also occurs on the gcc8. I'll keep an eye on the test and we for sure will notice if some real problem pops up again.

Thanks for all your hard work!

**Comment by jsiwrk** [comment]
Yes, I'm not satisfied either... The problem can (and ideally should) be analyzed more. Right now I cannot dedicate more time to this, but will add it to my todo in case I can in the future... Meanwhile it's great you have managed to work around the issue with clang (or so we hope...).
