### PR TITLE
Fixing the deleteStateOnFileDelete option

### LINKED ISSUE #4494: rsyslog leaves imfile state files behind (these get never deleted)
### Expected behavior

`imfile-state:INODE:HASH` get deleted once rsyslog finished processing the file corresponding to that inode after a log rotation occurred.

### Actual behavior

No deletion happening at all

### Steps to reproduce the behavior

1. Compile rsyslog with imfile support

   ~~~
   $ ./configure --enable-imfile
   $ make
   $ sudo make install
   ~~~

2. Create a dedicated mount point for the test (formatted with XFS preferably, so that inodes get reused)

   ~~~
   # mkdir -p /disk2/rsyslog
   ~~~

3. Create rsyslog.conf configuration file

   ~~~
   global(workDirectory="/disk2/rsyslog")
   module(load="imfile" mode="inotify")
   input(type="imfile"
      File="/disk2/input.log"
      Tag="imfile:"
      Severity="info"
      Facility="local6"
   )
   local6.info			/disk2/output.log
   ~~~

4. Create the following `logger.sh` script

~~~
#!/bin/sh

file="/disk2/input.log"
maxfilesize=$((8 * 1024 * 1024))

maxlogs=20

rotatelogs() {
	if [ -e "$file.$maxlogs" ]; then
		rm "$file.$maxlogs"
	fi

	for i in $(seq $(($maxlogs - 1)) -1 1); do
		[ -e "$file.$i" ] || continue
		mv "$file.$i" "$file.$(($i + 1))"
	done
	mv "$file" "$file.1"
	touch "$file"
}

statlogs() {
	echo
	date
	echo "$file $(stat -c "%i" $file)"
	for i in $(seq 1 $maxlogs); do
		[ -e "$file.$i" ] || break
		echo "$file.$i $(stat -c "%i" $file.$i)"
	done
}

seqnum=1
filler=$(printf "X%.0s" $(seq 1 250))
msgsize=$(printf "%09d $filler\n" $seqnum | wc -c)

writelog() {
	printf "%09d $filler\n" $seqnum >> "$file"
	let seqnum++
}

iters=$(($maxfilesize / $msgsize))
while :; do
	i=0; while [ $i -le 32140 ]; do
		if [ $(($seqnum % 1000)) -eq 0 ]; then
			echo $seqnum
		fi
		writelog
		let i++
	done
	rotatelogs
	statlogs
done
~~~

5. Execute rsyslogd with this configuration

   ~~~
   # /usr/local/sbin/rsyslogd -f ./rsyslog.conf -n
   ~~~

6. Generate logs using `logger.sh`

   ~~~
   # ./logger.sh
   ~~~

7. Wait for at least 20/30 rotations to occur, this will take a few minutes

8. Check content of `/disk2/rsyslog` directory, there are state files for files not existing anymore (INODE is gone)

### Environment
- rsyslog version: 8.2102.0.master
- platform: Fedora Rawhide (but doesn't apply really, I built from rsyslog master branch)

### PR DESCRIPTION
**Pull request by pearseimperva**
Fixes #4494

Fixes the `deleteStateOnFileDelete` option for imfile.

When the log file is deleted, imfile would attempt to delete the statefile but it was missing the `file_id` part of the statefile name. This means the statefiles were only removed in the log file is less than 512 characters, because for very small files the hash is not created. 

Added tests that checks that the statefile is deleted if `deleteStateOnFileDelete` is not specified, and that the statefile is not deleted if `deleteStateOnFileDelete = "off"`

### CODE REVIEW

**Comment by derekjsonar** [comment]
Hi @rgerhards, hope all is well.
Do you know how we can get past the test failure in the `solaris10x64` build?
```
FAIL: parsertest-snare_ccoff_udp2.sh
``` 
I don't see how it could be related to @pearseimperva's change.

Thanks.

**Comment by rgerhards** [comment]
@derekjsonar sorry for the late reply. The CI failures look like issues in CI itself. I have re-initiated the runs. Will now also look at the patch.

File: tests/imfile-statefile-delete.sh [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+template(name="outfmt" type="string" string="%msg:F,58:2%\n")
+if $msg contains "msgnum:" then
+	action(type="omfile" file=`echo $RSYSLOG_OUT_LOG` template="outfmt")
+'
+./inputfilegen -m $TESTMESSAGES > $RSYSLOG_DYNNAME.input
+inode=$(get_inode "$RSYSLOG_DYNNAME.input")
+startup
+wait_file_lines $RSYSLOG_OUT_LOG $TESTMESSAGES $RETRIES
+rm $RSYSLOG_DYNNAME.input
+# sleep a little to give rsyslog a chance to notice the deleted file
```
Comment (rgerhards) [inline tests/imfile-statefile-delete.sh]: timing via sleep is racy and results in flakes. Do we have a chance to synchronize the wait in a different way?

**Review by rgerhards — CHANGES_REQUESTED** [review]
more a "discussion request" on the test sync comment,.

File: tests/imfile-statefile-delete.sh (hunk 1 above)
Comment (pearseimperva) [reply tests/imfile-statefile-delete.sh]: Hi @rgerhards, thanks for looking into this PR. I remove the 2s sleep from `imfile-statefile-delete.sh`. It now waits until the state file is deleted, and if it waits for longer than 30s the test fails.

  `imfile-state-file-no-delete.sh` needs to wait long enough for rsyslog to notice the file was deleted and decide not to delete the state file because `deleteStateOnFileDelete="off”`. I haven't been able to think of a better way of doing this yet, but if you are able to point me in the right direction I'd be happy to change that test too. I decided to use sleeps in the tests after looking at `imfile-wildcards-dirs-multi.sh` and `imfile-endregex.sh` that do a similar thing.

Comment (rgerhards) [reply tests/imfile-statefile-delete.sh]: it's indeed tricky, I agree. Sounds like a good solution. Let's see what CI now says. I am willing to merge and see if this test becomes racy in the long term. If so, we (I ;-)) need to think of a different way to handle it.

**Review by rgerhards — APPROVED** [review]
